priority_rules:
  - name: hotfixes go first
    conditions:
      - "title~=^hotfix"
    priority: high

    allow_checks_interruption: true
queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=main
    merge_conditions:
      - check-success=required-ci
      - label=ship-it

pull_request_rules:
  - name: queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
